carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('catalog/<slug:category_slug>/', views.catalog, name='catalog'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('shipping/', views.shipping, name='shipping'),
]

sweet/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sweet import settings


from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from sweet import settings

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    prefix_default_language=True
)

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/models.py
from _decimal import Decimal, ROUND_HALF_UP

from django.db import models
from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Назва')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    is_visible = models.BooleanField(default=True)
    position = models.PositiveSmallIntegerField(default=0, unique=True)

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорію'
        verbose_name_plural = 'Категорії'

    def __str__(self) -> str:
        """Return a string representation of the object"""
        return self.name


class Products(models.Model):
    """The Products model represents a product in the database"""
    name = models.CharField(max_length=150, unique=True, verbose_name='Назва')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    is_visible = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True, verbose_name='Опис')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name="Зображення")
    image2 = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name="Зображення 2")
    image3 = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name="Зображення 3")
    image4 = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name="Зображення 4")
    image5 = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name="Зображення 5")
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name="Ціна")
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name="Знижка в %")
    quantity = models.PositiveIntegerField(default=0, verbose_name='Кількість')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категорія')

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукти'
        ordering = ('id',)

    def __str__(self) -> str:
        """ Return a string representation of the object"""
        return f'{self.name} Кількість - {self.quantity}'

    def get_absolute_url(self) -> str:
        """A method that generates the absolute URL for the product using the product's slug.
        Returns a string representing the absolute URL of the product."""
        return reverse('goods:product', kwargs={'product_slug': self.slug})

    def display_id(self) -> str:
        """Return a string representation of the object"""
        return f'{self.id:05}'

    def sell_price(self) -> Decimal:
        """Calculate the selling price of the product"""
        if self.discount:
            return Decimal(str(self.price - self.price * self.discount / 100)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

        return Decimal(str(self.price))

goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from goods.models import Categories, Products
from goods.utils import q_search


def catalog(request, category_slug=None):
    """A view function for rendering a catalog page with the option to filter by category, search query, and sale items.
     Parameters:
     - request: HttpRequest object
     - category_slug: str, optional category slug for filtering the products"""
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    if category_slug == 'all':
        goods = Products.objects.all()
    elif query is not None and query.strip():  # Проверяем, что параметр q присутствует и строка запроса не пуста
        goods = q_search(query)
    elif category_slug:  # Добавляем проверку на наличие category_slug
        category = get_object_or_404(Categories, slug=category_slug)
        goods = Products.objects.filter(category=category)
    else:
        goods = Products.objects.none()  # Если category_slug пуст, возвращаем пустой QuerySet

    if on_sale:
        goods = goods.filter(discount__gt=0)

    if order_by and order_by != 'default':
        goods = goods.order_by(order_by)

    paginator = Paginator(goods, 3)
    current_page = paginator.page(int(page))

    context = {
        'title': 'Home - Каталог',
        'goods': current_page,
        'slug_url': category_slug,
        'query': query,  # Передаем строку запроса в контекст
        'is_search': query is not None  # Добавляем флаг, указывающий, был ли выполнен поиск
    }
    return render(request, 'goods/catalog.html', context)


def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)
    context = {'product': product}

    return render(request, 'goods/product.html', context=context)

goods/templates/goods/catalog.html
{% extends 'base.html' %}
{% load static %}
{% load goods_tags %}
{% load i18n %}  <!-- Загрузка тегов перевода -->

{% block modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock %}

{% block cont %}
     <link rel="stylesheet" href="{% static 'deps/css/styles.css' %}">
     <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
     <div class="col-lg-10">

        <!-- {% trans 'Content on the page' %} -->

        <div class="row">

            <!-- {% trans 'Filters form' %} -->

            <div class="dropdown mb-2">
                <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                    aria-expanded="false">{% trans 'Filters' %}</button>


                <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url 'catalog:index' slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on"
                                {% if request.GET.on_sale == 'on' %}checked{% endif %} >
                        {% if request.GET.q %}
                            <input type="hidden" name="q" value="{{ request.GET.q }}">
                        {% endif %}
                        <label class="form-check-label" for="flexCheckDefault">
                            {% trans 'Promotional items' %}
                        </label>
                    </div>
                    <p class="text-white mx-3 mt-3">{% trans 'Sort by' %}:</p>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                        {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                        <label class="form-check-label" for="flexRadioDefault1">{% trans 'Default' %}</label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
                            {% if request.GET.order_by == 'price' %}checked{% endif %}>
                        <label class="form-check-label" for="flexRadioDefault2">{% trans 'From low to high' %}</label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
                              {% if request.GET.order_by == '-price' %}checked{% endif %}>
                        <label class="form-check-label" for="flexRadioDefault3">{% trans 'From high to low' %}</label>
                    </div>
                    <button type="submit" class="btn btn-primary mx-3 mt-3">{% trans 'Apply' %}</button>
                </form>
            </div>

            {% if request.GET.q %}
                <h3 class="mt-4">{% trans 'Search results for' %} "{{ request.GET.q }}"</h3>
                {% if not goods %}
                    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
                    <h2 class="mt-4">{% trans 'No results found for the query' %}</h2>
                {% endif %}
            {% elif request.GET.q is not None and not request.GET.q.strip %}
                 <h3 class="mt-4">{% trans 'No search query' %}</h3>
            {% endif %}


            {% if not goods %}
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" disabled >{% trans 'No products in this category yet' %}</button>
                </div>
{#                <div class="alert alert-info mt-4" role="alert">#}
{#                    {% trans 'No products in this category yet' %}#}
{#                </div>#}
{#                <h2 class="mt-4">{% trans 'No products in this category yet' %}</h2>#}
            {% else %}
                   {% for product in goods %}
                        <!-- {% trans 'Product card' %} -->
                        <div class="col-lg-4 col-md-6 p-4">
                            <div class="card border-primary rounded custom-shadow">
                                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" data-bs-toggle="modal" data-bs-target="#imageModal{{ forloop.counter }}">
                                <div class="card-body">
                                    <div class="text-center mb-3">
                                        <a href="{% url 'catalog:product' product.slug %}" class="product-link">
                                            {% autoescape off %}
                                            {% if product.headline %}
                                            {{ product.headline }}
                                            {% else %}
                                            {{ product.name }}
                                            {% endif %}
                                            {% endautoescape %}
                                        </a>
                                    </div>
                                    <p class="card-text">
                                        {% autoescape off %}
                                        {% if product.bodyline %}
                                        {{ product.bodyline|truncatechars:100}}
                                        {% else %}
                                        {{ product.description|truncatechars:35}}
                                        {% endif %}
                                        {% endautoescape %}
                                    </p>
                                    <p class="product_id">{% trans 'id' %}: {{ product.display_id }}</p>
                                    <div class="d-flex justify-content-between">
                                        {% if product.discount %}
                                        <p><s>{{ product.price }}</s> ₴</p>
                                        <p><strong>{{ product.sell_price }}₴</strong></p>
                                        <span class="badge bg-warning text-dark">{% trans 'Discount' %} {{ product.discount }}%</span>
                                        {% else %}
                                        <p><strong>{{ product.price }} ₴</strong></p>
                                        {% endif %}
                                        <a href="{% url 'cart:cart_add' %}" class="btn add-to-cart" data-product-id='{{ product.id }}'>
                                            {% csrf_token %}
                                            <img class="mx-1" src="{% static 'deps/icons/cart-plus.svg' %}" alt="{% trans 'Catalog Icon' %}" width="32" height="32">
                                        </a>
                                    </div>
                                </div>
                                <!-- {% trans 'Modal window' %} -->
                                <div class="modal fade" id="imageModal{{ forloop.counter }}" tabindex="-1" aria-labelledby="imageModalLabel{{ forloop.counter }}" aria-hidden="true">
                                    <div class="modal-dialog modal-lg">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="imageModalLabel{{ forloop.counter }}">{{ product.name }}</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% trans 'Close' %}"></button>
                                            </div>
                                            <div class="modal-body">
                                                <div id="carouselImages{{ forloop.counter }}" class="carousel slide" data-bs-ride="carousel">
                                                    <div class="carousel-inner">
                                                        {% if product.image %}
                                                        <div class="carousel-item active">
                                                            <img src="{{ product.image.url }}" class="d-block w-100" alt="{% trans 'Image 1' %}">
                                                        </div>
                                                        {% endif %}
                                                        {% if product.image2 %}
                                                        <div class="carousel-item">
                                                            <img src="{{ product.image2.url }}" class="d-block w-100" alt="{% trans 'Image 2' %}">
                                                        </div>
                                                        {% endif %}
                                                        {% if product.image3 %}
                                                        <div class="carousel-item">
                                                            <img src="{{ product.image3.url }}" class="d-block w-100" alt="{% trans 'Image 3' %}">
                                                        </div>
                                                        {% endif %}
                                                        {% if product.image4 %}
                                                        <div class="carousel-item">
                                                            <img src="{{ product.image4.url }}" class="d-block w-100" alt="{% trans 'Image 4' %}">
                                                        </div>
                                                        {% endif %}
                                                        {% if product.image5 %}
                                                        <div class="carousel-item">
                                                            <img src="{{ product.image5.url }}" class="d-block w-100" alt="{% trans 'Image 5' %}">
                                                        </div>
                                                        {% endif %}
                                                    </div>
                                                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselImages{{ forloop.counter }}" data-bs-slide="prev">
                                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                                        <span class="visually-hidden">{% trans 'Previous' %}</span>
                                                    </button>
                                                    <button class="carousel-control-next" type="button" data-bs-target="#carouselImages{{ forloop.counter }}" data-bs-slide="next">
                                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                                        <span class="visually-hidden">{% trans 'Next' %}</span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- {% trans 'Rest of the product card' %} -->
                            </div>
                        </div>
                   {% endfor %}
            {% endif %}



        </div>
        <!-- {% trans 'Pagination' %} -->
        {% if goods %}
            <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center my-4">
                <div class="custom-shadow d-flex">
                    <li class="page-item {% if not goods.has_previous %}disabled{% endif %}">
                        <a class="page-link" href="{% if goods.has_previous %}?{% change_params page=goods.previous_page_number %}{% else %}#{% endif %}">{% trans 'Back' %}</a>
                    </li>

                    {% for page in goods.paginator.page_range %}
                        {% if page >= goods.number|add:-2  and page <= goods.number|add:2 %}
                             <li class="page-item {% if goods.number == page %} active {% endif %} ">
                                 <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                             </li>
                        {% endif %}
                    {% endfor %}

                    <li class="page-item {% if not goods.has_next %}disabled{% endif %}">
                        <a class="page-link" href="
                        {% if goods.has_next %}?{% change_params page=goods.next_page_number %}{% else %}#{% endif %}">{% trans 'Next' %}</a>
                    </li>
                </div>
            </ul>
        </nav>
    </div>
        {% endif %}

{% endblock %}


{% block footer %}
     <footer class="py-4 bg-dark fixed-bottom" >
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; So Sweet Studio 2024</p>
        </div>
    </footer>
{% endblock %}

goods/templates/goods/product.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}  <!-- Загрузка тегов перевода -->

{% block modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock %}

{% block cont %}
<link rel="stylesheet" href="{% static 'deps/css/product.css' %}">
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card mb-4 custom-shadow">
                <div class="row g-0">
                    <!-- {% trans 'Thumbnails' %} -->
                      <div class="col-md-6">
                        <div class="image-container">
                            <div class="carousel-container">
                                <div id="carouselImages" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3500">
                            <div class="carousel-inner">
                                {% if product.image %}
                                <div class="carousel-item active">
                                    <img src="{{ product.image.url }}" class="d-block w-100" alt="{% trans 'Image 1' %}">
                                </div>
                                {% endif %}
                                {% if product.image2 %}
                                <div class="carousel-item">
                                    <img src="{{ product.image2.url }}" class="d-block w-100" alt="{% trans 'Image 2' %}">
                                </div>
                                {% endif %}
                                {% if product.image3 %}
                                <div class="carousel-item">
                                    <img src="{{ product.image3.url }}" class="d-block w-100" alt="{% trans 'Image 3' %}">
                                </div>
                                {% endif %}
                                {% if product.image4 %}
                                <div class="carousel-item">
                                    <img src="{{ product.image4.url }}" class="d-block w-100" alt="{% trans 'Image 4' %}">
                                </div>
                                {% endif %}
                                {% if product.image5 %}
                                <div class="carousel-item">
                                    <img src="{{ product.image5.url }}" class="d-block w-100" alt="{% trans 'Image 5' %}">
                                </div>
                                {% endif %}
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#carouselImages" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">{% trans 'Previous' %}</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carouselImages" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">{% trans 'Next' %}</span>
                            </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- {% trans 'Product description' %} -->
                    <div class="col-md-6">
                        <div class="card-body d-flex flex-column justify-content-center align-items-center">
                            <p class="product_id">{% trans 'id' %}: {{ product.display_id }}</p>
                            <p class="card-text">{% trans 'Price' %}: <strong>{{ product.sell_price }} ₴</strong></p>
                            <h3 class="card-title product-name">{{ product.name }}</h3>
                            <p class="card-text">{{ product.description }}</p>
                            <a href="{% url 'carts:cart_add' %}" class="btn btn-dark add-to-cart" data-product-id='{{ product.id }}'>
                                {% csrf_token %}
                                {% trans 'Add to cart' %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}