goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('catalog/<slug:category_slug>/', views.catalog, name='catalog'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('shipping/', views.shipping, name='shipping'),
]

sweet/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sweet import settings


from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from sweet import settings

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    prefix_default_language=True
)

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users_cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User


class OrderitemQueryset(models.QuerySet):

    def total_price(self) -> int:
        """Method for getting total price of order"""
        return sum(cart.products_price() for cart in self)

    def total_quantity(self) -> int:
        """Method for getting total quantity of order"""
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Користувач",
                             default=None)
    first_name = models.CharField(max_length=100, default='', verbose_name="Имя")
    last_name = models.CharField(max_length=100, default='', verbose_name="Фамилия")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення замовлення")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефону")
    requires_delivery = models.BooleanField(default=False, verbose_name="Потрібна доставка")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адреса доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при отриманні")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обробці', verbose_name="Статус замовлення")

    class Meta:
        db_table = "order"
        verbose_name = "Замовлення"
        verbose_name_plural = "Замовлення"

    def __str__(self) -> str:
        """Method for getting string representation of order"""
        return f"Замовлення № {self.pk} | Покупець {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Замовлення")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт",
                                default=None)
    name = models.CharField(max_length=150, verbose_name="Назва")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Ціна")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажу")

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданий товар"
        verbose_name_plural = "Продані товари"

    objects = OrderitemQueryset.as_manager()

    def products_price(self) -> float:
        """Method for getting products price"""
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self) -> str:
        """Method for getting string representation of order item"""
        return f"Товар {self.name} | Замовлення № {self.order.pk}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            username=username,
            email=email,
            password=password,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    objects = CustomUserManager()

    class Meta:
        db_table = 'user'
        verbose_name = 'Користувача'
        verbose_name_plural = 'Користувачі'

    def __str__(self) -> str:
        """Return username"""
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    error_messages = {
        'invalid_login': "Будь ласка, введіть правильні ім'я користувача та пароль. Обидва поля можуть бути чутливими до регістру",
        'inactive': "Цей обліковий запис неактивний",
    }

    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user
# class UserRegistrationForm(UserCreationForm):
#     email = forms.EmailField(required=True)
#
#     class Meta:
#         model = User
#         fields = ('username', 'email', 'password1', 'password2')
#
#     def save(self, commit=True):
#         user = super().save(commit=False)
#         user.email = self.cleaned_data['email']
#         if commit:
#             user.save()
#         return user


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from carts.models import Cart
from orders.models import Order, OrderItem
from users.forms import UserLoginForm, UserRegistrationForm, ProfileForm
from django.contrib.auth import authenticate
from django.utils.translation import gettext_lazy as _

def login(request):
    """ A function to handle user login. It takes a request object as a parameter and performs
    authentication and form validation. """
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(
                username=username,
                password=password,
                backend='django.contrib.auth.backends.ModelBackend'
            )

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, _('%(username)s, Ви увійшли до облікового запису') % {'username': username})  # Используем gettext_lazy с форматированием строк

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
    context = {
        'title': _('Home - Авторизація'),  # Используем gettext_lazy
        'form': form
    }
    return render(request, 'users/login.html', context)



def registration(request):
    """A function that handles user registration"""
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            user = authenticate(username=user.username, password=form.cleaned_data['password1'],
                                backend='django.contrib.auth.backends.ModelBackend')
            if user is not None:
                auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)
            messages.success(request, _(f'{user.username}, Ви успішно зареєструвалися та увійшли до облікового запису'))  # Используем gettext
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': _('Home - Реєстрація'),  # Используем gettext
        'form': form
    }
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    """A view function to handle the user profile, allowing them to update their profile information
    and displaying their order history."""
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, _('профіль успішно оновлено'))  # Используем gettext
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        initial_data = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'username': request.user.username,
            'email': request.user.email,
        }
        form = ProfileForm(instance=request.user, initial=initial_data)

    orders = (
        Order.objects.filter(user=request.user)
            .prefetch_related(
                Prefetch(
                    'orderitem_set',
                    queryset=OrderItem.objects.select_related('product'),
                )
            ).order_by('-id')
    )

    context = {
        'title': _('Home - Кабінет'),  # Используем gettext
        'form': form,
        'orders': orders,
    }
    return render(request, 'users/profile.html', context)

def users_cart(request):
    """A view function to display the user's cart"""
    return render(request, 'users/users_cart.html')

@login_required
def logout(request):
    """A view function to logout the user"""
    username = request.user.username
    logout_message_part1 = _("{username}").format(username=username)
    logout_message_part2 = _("Ви вийшли з облікового запису")
    logout_message = f"{logout_message_part1} {logout_message_part2}"
    messages.success(request, logout_message)
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}
{% load i18n %}

{% block modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock %}

{% block cont %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">{% trans "Авторизація" %}</h2>
                    <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}
                        {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                        {% endif %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">{% trans "Ім'я користувача" %}</label>
                            <input type="text" class="form-control"
                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                            name="username" id="id_username"
                            placeholder="{% trans "Введіть ім'я користувача" %}"
                            required>
                         </div>

                        <div class="mb-3">
                            <label for="id_password" class="form-label">{% trans "Пароль" %}</label>
                            <input type="password" class="form-control" name="password" id="id_password"
                            placeholder="{% trans "Введіть ваш пароль" %}" required>
                        </div>

                        <button type="submit" class="btn btn-dark btn-block">{% trans "Увійти" %}</button>
                    </form>
                    <div class="mt-3">
                        <a href="{% url 'user:registration' %}">{% trans "Створити акаунт" %}</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>{% trans "Або авторизуйтесь через:" %}</p>
                        <a href="{% provider_login_url 'github' %}" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load carts_tags %}
{% load i18n %}

{% block cont %}
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">{% trans "Профіль користувача" %}</h3>
                        <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    {% if user.image %}
                                        <img src="{{ user.image.url }}"
                                        alt="{% trans "Аватар користувача" %}" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                    {% else %}
                                        <img src="{% static 'deps/images/baseavatar.jpg' %}"
                                        alt="{% trans "Аватар користувача" %}" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                    {% endif %}
                                        <input type="file" class="form-control mt-3" id="id_image"
                                               name="image"
                                               accept="image/*">
                                               {% if form.image.errors %}
                                                   <div class="alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                               {% endif %}

                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">{% trans "Ім'я*" %}</label>
                                    <input type="text" class="form-control" id="id_first_name"
                                           name="first_name"
                                           placeholder="{% trans "Введіть ваше ім'я" %}"
                                           value="{{ form.instance.first_name }}"
                                           required>
                                    {% if form.first_name.errors %}
                                        <div class="alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}

                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">{% trans "Прізвище*" %}</label>
                                    <input type="text" class="form-control" id="id_last_name"
                                        name="last_name"
                                        placeholder="{% trans "Введіть ваше прізвище" %}"
                                        value="{{ form.last_name.value }}"
                                        required>
                                        {% if form.last_name.errors %}
                                            <div class="alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">{% trans "Ім'я користувача*" %}</label>
                                    <input type="text" class="form-control" id="id_username"
                                        name="username"
                                        placeholder="{% trans "Введіть ім'я користувача" %}"
                                        value="{{ form.username.value }}"
                                        required>
                                        {% if form.username.errors %}
                                            <div class="alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">{% trans "Email*" %}</label>
                                    <input type="email" class="form-control" id="id_email"
                                        name="email"
                                        placeholder="{% trans "Введіть ваш email *youremail@example.com" %}"
                                        value="{{ form.email.value }}"
                                        required>
                                        {% if form.email.errors %}
                                            <div class="alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                        {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">{% trans "Зберегти" %}</button>
                        </form>
                    </div>
                </div>
                <!-- Корзина -->
                {% user_carts request as carts %}
                <div class="col-md-7">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">{% trans "Кошик" %}</h3>
                        <div class="container" id="cart-items-container">
                            <!-- Разметка корзины -->
                            {% include 'carts/includes/included_cart.html' %}
                            <!-- Закончилась разметка корзины -->
                        </div>
                    </div>
                </div>
                <!-- Оформленные заказы -->
                <div class="col-md-12">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">{% trans "Мої замовлення" %}</h3>
                        <!-- Разметка заказов -->
                        <div class="container">
 <div class="accordion" id="accordionExample">
                            {% for order in orders %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        {% trans "Замовлення № " %}{{ order.id }} - {{ order.created_timestamp }} | {% trans "Статус:" %} <strong class="mx-2">{{order.status}}</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>{% trans "Товар" %}</th>
                                                    <th>{% trans "Кількість" %}</th>
                                                    <th>{% trans "Ціна" %}</th>
                                                    <th>{% trans "Загальна вартість" %}</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-white" href="{% url 'goods:product' item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }}</td>
                                                    <td>{{ item.products_price }}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock %}

{% block cont %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">{% trans "Реєстрація" %}</h2>
                    <form action="{% url 'users:registration' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">{% trans "Им'я*" %}</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %} "
                                    name="first_name"
                                    placeholder="{% trans "Введіть ваше им'я" %}" required>
                                    {% if form.first_name.errors %}
                                        <div class="alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">{% trans "Прізвище*" %}</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %} "
                                    name="last_name"
                                    placeholder="{% trans "Введіть ваше прізвище" %}" required>
                                    {% if form.last_name.errors %}
                                        <div class="alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">{% trans "Им'я користувача*" %}</label>
                                <input type="text" class="form-control" id="id_username"
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %} "
                                    name="username"
                                    placeholder="{% trans "Введіть ім'я користувача" %}" required>
                                    {% if form.user_name.errors %}
                                        <div class="alert-danger alert-dismissible fade show">{{ form.user_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">{% trans "Email*" %}</label>
                                <input type="email" class="form-control" id="id_email"
                                    value="{% if form.email.value %}{{ form.email.value }}{% endif %} "
                                    name="email"
                                    placeholder="{% trans "Введіть ваш email" %}" required>
                                    {% if form.email.errors %}
                                        <div class="alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">{% trans "Пароль*" %}</label>
                                <input type="password" class="form-control" id="id_password1"
                                    value="{% if form.password1.value %}{{ form.password1.value }}{% else %}{{ '' }}{% endif %}"
                                    name="password1"
                                    placeholder="{% trans "Введіть пароль" %}" required>

                                    {% if form.password1.errors %}
                                        <div class="alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">{% trans "Підтвердження пароля*" %}</label>
                                <input type="password" class="form-control" id="id_password1"
                                    value="{% if form.password2.value %}{{ form.password2.value }}{% else %}{{ '' }}{% endif %}"
                                    name="password2"
                                    placeholder="{% trans "Підтвердіть пароль" %}" required>
                                    {% if form.password2.errors %}
                                        <div class="alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btn-dark btn-block">{% trans "Зареєструватися" %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/users_cart.html
{% extends 'base.html' %}
{% load static %}
{% load carts_tags %}
{% load i18n %}

{% block cont %}
    {% user_carts request as carts %}
     <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">{% trans "Кошик" %}</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include 'carts/includes/included_cart.html' %}
                        <!-- Закончилась разметка корзины -->
                    </div>
            </div>
        </div>
    </div>
{% endblock %}